"""
backend/api/pdf.py — Self-contained PDF generation for DataPilot.

Copied from ui/report_export.py so the backend has no dependency on the
Streamlit ui/ package. Uses fpdf2 (pure Python, no system libs required).

Public API:
    build_pdf(task, narrative, recommendation, metric, cost_usd) -> bytes
"""
from __future__ import annotations

import re
from datetime import datetime
from io import BytesIO

from fpdf import FPDF, XPos, YPos

_NAVY   = (15,  40,  80)
_BLUE   = (30,  90, 180)
_DARK   = (30,  30,  30)
_MUTED  = (100, 100, 100)
_WHITE  = (255, 255, 255)
_LIGHT  = (245, 247, 252)
_BORDER = (210, 218, 235)
_GREEN  = (22, 130, 70)


# A spaced em/en dash between words is doing a comma's job, so make it one.
# Mapping it to "-" (as the table below still does for every other case) turned
# parenthetical asides into hyphen-strewn prose: "drop-off is the risk - the
# biggest one" reads as a compound word that lost its way.
#
# Deliberately limited to letter-space-dash-space-letter. A dash between digits
# is a range ("7 - 10"), and rewriting that to "7, 10" would change the meaning.
_SPACED_DASH_RE = re.compile(r"(?<=[A-Za-z])\s+[\u2014\u2013]\s+(?=[A-Za-z])")


def _clean(text: str) -> str:
    text = _SPACED_DASH_RE.sub(", ", text)
    replacements = {
        "\u2014": "-", "\u2013": "-", "\u2019": "'", "\u2018": "'",
        "\u201c": '"', "\u201d": '"', "\u2026": "...", "\u2192": "->",
        "\u2190": "<-", "\u00b7": "*", "\u2022": "*", "\u2713": "[OK]",
        "\u2717": "[X]", "\u2705": "[OK]", "\u26a0": "[!]", "\ufe0f": "",
        "\u2728": "*",
    }
    for src, dst in replacements.items():
        text = text.replace(src, dst)
    return text.encode("latin-1", errors="ignore").decode("latin-1")


class _PDF(FPDF):
    def __init__(self, task: str, metric: str):
        super().__init__()
        self._task   = task
        self._metric = metric
        self.set_margins(20, 20, 20)
        self.set_auto_page_break(auto=True, margin=20)

    def header(self):
        self.set_fill_color(*_NAVY)
        self.rect(0, 0, 210, 14, style="F")
        self.set_xy(20, 3)
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(*_WHITE)
        self.cell(0, 8, "DataPilot - Analysis Report", new_x=XPos.RIGHT, new_y=YPos.TOP)
        self.set_xy(-50, 3)
        self.set_font("Helvetica", "", 8)
        self.cell(30, 8, datetime.now().strftime("%Y-%m-%d %H:%M"), align="R")
        self.set_text_color(*_DARK)
        self.ln(16)

    def footer(self):
        self.set_y(-12)
        self.set_font("Helvetica", "", 7)
        self.set_text_color(*_MUTED)
        self.cell(0, 6, f"Page {self.page_no()} - Generated by DataPilot", align="C")


_HTML_COMMENT_RE = re.compile(r"<!--.*?-->", re.DOTALL)
_INLINE_CODE_RE  = re.compile(r"`([^`]*)`")

# A bullet marker is only a bullet when whitespace follows it. Without that
# requirement `**Bottom Line**` reads as a `*` bullet, and the old leading-marker
# strip (`^[\s\-\*•]+`) then ate the opening `**` — which both left a literal
# `**` at the end of the line and shifted every remaining delimiter on it by one,
# inverting bold and plain for the rest of the paragraph.
_BULLET_RE = re.compile(r"^(\s*)[-*•]\s+(.*)$")

# A line that is nothing but bold text is a section heading. The model writes
# headings that way (`**Key Findings**`) rather than with `##`.
_BOLD_HEADING_RE = re.compile(r"^\*\*(.+?)\*\*:?\s*$")

_BLOCKQUOTE_RE = re.compile(r"^\s*>\s?(.*)$")

_MARKER_ONLY_RE = re.compile(r"[-*•_]{1,}")

# Non-greedy, and tolerant of `*` inside the span. `[^*]+` could not match
# `**power (user_segment: power)**` once emphasis appeared within a bold run.
_BOLD_SPAN_RE = re.compile(r"(\*\*.+?\*\*)")


def _strip_md_bold(text: str) -> list[tuple[bool, str]]:
    parts: list[tuple[bool, str]] = []
    for chunk in _BOLD_SPAN_RE.split(text):
        if len(chunk) > 4 and chunk.startswith("**") and chunk.endswith("**"):
            parts.append((True, chunk[2:-2]))
        elif chunk:
            parts.append((False, chunk))
    return parts


def _write_mixed(
    pdf: FPDF,
    text: str,
    font_size: int = 10,
    indent: float | None = None,
    base_style: str = "",
) -> None:
    """Write inline markdown, optionally hanging-indented.

    `indent` moves the left margin, not just the cursor: `write()` wraps to the
    margin, so setting only the cursor left every continuation line of a bullet
    flush against the page edge while its first line was indented.
    """
    prev_margin = pdf.l_margin
    if indent is not None:
        pdf.set_left_margin(indent)
        pdf.set_x(indent)
    try:
        for is_bold, segment in _strip_md_bold(_INLINE_CODE_RE.sub(r"\1", text)):
            style = "B" if is_bold else base_style
            pdf.set_font("Helvetica", style, font_size)
            pdf.write(5.5, _clean(segment))
    finally:
        if indent is not None:
            pdf.set_left_margin(prev_margin)


def _section_heading(pdf: FPDF, text: str) -> None:
    pdf.ln(3)
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(*_BLUE)
    pdf.set_x(20)
    pdf.cell(0, 7, _clean(text), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    y = pdf.get_y() - 1
    pdf.set_draw_color(*_BLUE)
    pdf.line(20, y, 190, y)
    pdf.set_text_color(*_DARK)
    pdf.ln(1.5)


def _render_markdown(pdf: FPDF, md: str) -> None:
    # `<!-- details -->` is a layout marker for the web UI. It was printed
    # verbatim into the report.
    md = _HTML_COMMENT_RE.sub("", md)

    for raw_line in md.splitlines():
        line = raw_line.rstrip()
        stripped = line.strip()

        bold_heading = _BOLD_HEADING_RE.match(stripped)
        bullet = _BULLET_RE.match(line)
        quote = _BLOCKQUOTE_RE.match(line)

        # A bullet whose content is only bold text is still a heading — the
        # model writes "- **Key Findings**" as often as "**Key Findings**".
        if bullet and not bold_heading:
            inner = _BOLD_HEADING_RE.match(bullet.group(2).strip())
            if inner:
                bold_heading, bullet = inner, None

        if bold_heading:
            _section_heading(pdf, bold_heading.group(1))
        elif line.startswith("## "):
            pdf.ln(3)
            pdf.set_font("Helvetica", "B", 11)
            pdf.set_text_color(*_BLUE)
            pdf.cell(0, 7, _clean(line[3:].strip()), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
            y = pdf.get_y() - 1
            pdf.set_draw_color(*_BLUE)
            pdf.line(20, y, 190, y)
            pdf.set_text_color(*_DARK)
            pdf.ln(1)
        elif line.startswith("### "):
            pdf.ln(2)
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(*_NAVY)
            pdf.cell(0, 6, _clean(line[4:].strip()), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
            pdf.set_text_color(*_DARK)
        elif bullet:
            text = bullet.group(2).strip()
            if not text:
                continue  # a marker with nothing after it printed a bare "-"
            # Second level for indented source bullets.
            depth = 1 if len(bullet.group(1)) >= 2 else 0
            marker_x = 23 + depth * 6
            text_x   = marker_x + 5

            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(*_DARK)
            pdf.set_x(marker_x)
            pdf.cell(4, 5.5, "-" if depth == 0 else "·")
            _write_mixed(pdf, text, indent=text_x)
            pdf.ln(6)
        elif quote:
            text = quote.group(1).strip()
            if not text:
                continue
            # Rule down the left edge, the way a pull-quote reads on the web.
            top = pdf.get_y()
            pdf.set_text_color(*_MUTED)
            _write_mixed(pdf, text, font_size=9, indent=26, base_style="I")
            pdf.ln(6)
            pdf.set_draw_color(*_BORDER)
            pdf.set_line_width(0.6)
            pdf.line(21, top, 21, pdf.get_y() - 2)
            pdf.set_line_width(0.2)
            pdf.set_text_color(*_DARK)
        elif not stripped or _MARKER_ONLY_RE.fullmatch(stripped):
            # A marker with no content: an empty list item the model emitted, or
            # a `---` rule. Neither carries meaning in the report, and the bullet
            # branch cannot catch them because it requires text after the marker.
            pdf.ln(2)
        else:
            pdf.set_x(20)
            pdf.set_font("Helvetica", "", 10)
            _write_mixed(pdf, line.strip(), indent=20)
            pdf.ln(6)


def build_pdf(
    task: str,
    narrative: str,
    recommendation: str,
    metric: str = "",
    cost_usd: float = 0.0,
) -> bytes:
    pdf = _PDF(task=task, metric=metric)
    pdf.add_page()

    # Title card
    pdf.set_fill_color(*_LIGHT)
    pdf.set_draw_color(*_BORDER)
    pdf.rect(20, pdf.get_y(), 170, 22, style="FD")
    pdf.set_xy(24, pdf.get_y() + 3)
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(*_NAVY)
    pdf.multi_cell(162, 7, _clean(task), align="L")
    pdf.set_font("Helvetica", "", 8)
    pdf.set_text_color(*_MUTED)
    meta_parts = []
    if metric:
        meta_parts.append(f"Metric: {metric}")
    if cost_usd > 0:
        meta_parts.append(f"API cost: ${cost_usd:.4f}")
    if meta_parts:
        pdf.set_x(24)
        pdf.cell(0, 5, "  ·  ".join(meta_parts))
    pdf.ln(10)

    # Recommendation callout
    if recommendation:
        body = _clean(recommendation)
        pdf.set_font("Helvetica", "", 9)
        # Measure before drawing. The box used to be a fixed 14mm regardless of
        # content, so anything past two lines ran outside its own border.
        lines = len(pdf.multi_cell(162, 5, body, dry_run=True, output="LINES"))
        box_h = 9 + lines * 5

        top = pdf.get_y()
        pdf.set_fill_color(*_GREEN)
        pdf.rect(20, top, 170, 2, style="F")
        pdf.set_fill_color(235, 248, 240)
        pdf.set_draw_color(*_GREEN)
        pdf.rect(20, top + 2, 170, box_h, style="FD")

        # Label on its own line. Setting it beside the text meant a 20mm cell
        # against a wider string, so the body overprinted the label.
        pdf.set_xy(24, top + 5)
        pdf.set_font("Helvetica", "B", 7.5)
        pdf.set_text_color(*_GREEN)
        pdf.cell(0, 4, "RECOMMENDATION", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.set_xy(24, pdf.get_y() + 0.5)
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(*_DARK)
        pdf.multi_cell(162, 5, body)
        pdf.set_y(top + box_h + 2)
        pdf.ln(4)

    # Narrative
    pdf.set_text_color(*_DARK)
    _render_markdown(pdf, narrative)

    buf = BytesIO()
    pdf.output(buf)
    return buf.getvalue()
