"""
tests/test_db_tools.py — Unit tests for tools/db_tools.py

Uses the tmp_duckdb fixture (minimal in-memory-equivalent DuckDB).
Does NOT touch the full dau_experiment.db.
"""

import pandas as pd
import pytest
import duckdb

from tools.db_tools import DBConnection


def test_duckdb_connection_succeeds(tmp_duckdb):
    """Connecting to a valid DuckDB file returns success with correct table count."""
    db = DBConnection("duckdb", path=tmp_duckdb)
    result = db.test_connection()
    assert result["success"] is True
    assert result["table_count"] == 1


def test_postgres_connection_fails_gracefully():
    """Bad Postgres credentials return {success: False, error: str} — no exception raised."""
    db = DBConnection("postgres", host="localhost", port=5432,
                      dbname="nonexistent_db", user="nobody", password="wrong")
    result = db.test_connection()
    assert result["success"] is False
    assert isinstance(result["error"], str)
    assert len(result["error"]) > 0


def test_inspect_schema_format(tmp_duckdb):
    """Schema string contains TABLE: markers and -- inline comments."""
    db = DBConnection("duckdb", path=tmp_duckdb)
    schema = db.inspect_schema()
    assert "TABLE:" in schema
    assert "--" in schema          # inline comments from SCHEMA_COMMENTS
    assert "events" in schema      # table name present


def test_query_returns_dataframe(tmp_duckdb):
    """SQL query returns a DataFrame with the expected columns and row count."""
    db = DBConnection("duckdb", path=tmp_duckdb)
    df = db.query("SELECT user_id, dau_flag FROM events ORDER BY user_id")
    assert isinstance(df, pd.DataFrame)
    assert list(df.columns) == ["user_id", "dau_flag"]
    assert len(df) == 3


def test_query_rejects_non_select(tmp_duckdb):
    db = DBConnection("duckdb", path=tmp_duckdb)
    with pytest.raises(ValueError, match="Only SELECT"):
        db.query("PRAGMA show_tables")


def test_query_allows_leading_comments_before_select(tmp_duckdb):
    db = DBConnection("duckdb", path=tmp_duckdb)
    df = db.query("-- generated by model\n/* reviewed */\nSELECT COUNT(*) AS n FROM events")
    assert df["n"].iloc[0] == 3


def test_inspect_schema_quotes_unusual_duckdb_identifiers(tmp_path):
    path = str(tmp_path / "odd.db")
    con = duckdb.connect(path)
    con.execute('CREATE TABLE "odd table" ("select" INTEGER, "two words" VARCHAR)')
    con.execute('INSERT INTO "odd table" VALUES (1, \'a\')')
    con.close()

    schema = DBConnection("duckdb", path=path).inspect_schema()
    assert "TABLE: odd table" in schema
    assert "select" in schema
    assert "two words" in schema
