"""
tests/test_db_tools.py — Unit tests for tools/db_tools.py

Uses the tmp_duckdb fixture (minimal in-memory-equivalent DuckDB).
Does NOT touch the full dau_experiment.db.
"""

import pandas as pd
import pytest
import duckdb

from tools.db_tools import DBConnection, dialect_label


def test_dialect_label_covers_warehouse_backends():
    assert dialect_label("mysql") == "MySQL"
    assert "BigQuery" in dialect_label("bigquery")
    assert dialect_label("postgres") == "PostgreSQL"


def test_mysql_init_and_connection_fails_gracefully():
    db = DBConnection(
        "mysql",
        host="127.0.0.1",
        port=3306,
        dbname="nonexistent_db",
        user="nobody",
        password="wrong",
    )
    result = db.test_connection()
    assert result["success"] is False
    assert isinstance(result["error"], str)
    assert len(result["error"]) > 0


def test_bigquery_init_requires_credentials():
    with pytest.raises(ValueError, match="credentials"):
        DBConnection("bigquery", project_id="p", dataset="d")


def test_bigquery_init_ok():
    creds = (
        '{"type":"service_account","client_email":"a@b.com",'
        '"private_key":"-----BEGIN PRIVATE KEY-----\\nX\\n-----END PRIVATE KEY-----\\n"}'
    )
    db = DBConnection(
        "bigquery",
        project_id="my-project",
        dataset="analytics",
        credentials_json=creds,
    )
    assert db.backend == "bigquery"


def test_duckdb_connection_succeeds(tmp_duckdb):
    """Connecting to a valid DuckDB file returns success with correct table count."""
    db = DBConnection("duckdb", path=tmp_duckdb)
    result = db.test_connection()
    assert result["success"] is True
    assert result["table_count"] == 1


def test_postgres_connection_fails_gracefully():
    """Bad Postgres credentials return {success: False, error: str} — no exception raised."""
    db = DBConnection("postgres", host="localhost", port=5432,
                      dbname="nonexistent_db", user="nobody", password="wrong")
    result = db.test_connection()
    assert result["success"] is False
    assert isinstance(result["error"], str)
    assert len(result["error"]) > 0


def test_inspect_schema_format(tmp_duckdb):
    """Schema string contains TABLE: markers and -- inline comments."""
    db = DBConnection("duckdb", path=tmp_duckdb)
    schema = db.inspect_schema()
    assert "TABLE:" in schema
    assert "--" in schema          # inline comments from SCHEMA_COMMENTS
    assert "events" in schema      # table name present


def test_query_returns_dataframe(tmp_duckdb):
    """SQL query returns a DataFrame with the expected columns and row count."""
    db = DBConnection("duckdb", path=tmp_duckdb)
    df = db.query("SELECT user_id, dau_flag FROM events ORDER BY user_id")
    assert isinstance(df, pd.DataFrame)
    assert list(df.columns) == ["user_id", "dau_flag"]
    assert len(df) == 3


def test_query_rejects_non_select(tmp_duckdb):
    db = DBConnection("duckdb", path=tmp_duckdb)
    with pytest.raises(ValueError, match="Only SELECT"):
        db.query("PRAGMA show_tables")


def test_query_allows_leading_comments_before_select(tmp_duckdb):
    db = DBConnection("duckdb", path=tmp_duckdb)
    df = db.query("-- generated by model\n/* reviewed */\nSELECT COUNT(*) AS n FROM events")
    assert df["n"].iloc[0] == 3


def test_inspect_schema_quotes_unusual_duckdb_identifiers(tmp_path):
    path = str(tmp_path / "odd.db")
    con = duckdb.connect(path)
    con.execute('CREATE TABLE "odd table" ("select" INTEGER, "two words" VARCHAR)')
    con.execute('INSERT INTO "odd table" VALUES (1, \'a\')')
    con.close()

    schema = DBConnection("duckdb", path=path).inspect_schema()
    assert "TABLE: odd table" in schema
    assert "select" in schema
    assert "two words" in schema


# ── Postgres multi-schema discovery ───────────────────────────────────────────

def _pg_conn():
    return DBConnection(
        "postgres",
        host="127.0.0.1", port=5432, dbname="d", user="u", password="p",
    )


def test_postgres_tables_span_all_schemas(monkeypatch):
    """Warehouses keep tables in named schemas; public-only made them invisible."""
    db = _pg_conn()
    captured = {}

    def fake_query(sql, params=None):
        captured["sql"] = sql
        return pd.DataFrame({
            "table_schema": ["public", "public", "analytics", "marts"],
            "table_name":   ["events", "weird.name", "sessions", "orders"],
        })

    monkeypatch.setattr(db, "_query_postgres", fake_query)
    names = db._get_tables_postgres()
    # Bare names for dot-free public tables (annotations stay valid); qualified
    # otherwise — including a public table whose own name contains a dot.
    assert names == ["events", "public.weird.name", "analytics.sessions", "marts.orders"]
    assert "pg_catalog" in captured["sql"]  # system schemas excluded


def test_postgres_columns_bind_qualified_schema(monkeypatch):
    db = _pg_conn()
    captured = {}

    def fake_query(sql, params=None):
        captured["params"] = params
        return pd.DataFrame({"column_name": ["id"], "data_type": ["integer"]})

    monkeypatch.setattr(db, "_query_postgres", fake_query)

    db._get_columns_postgres("marts.orders")
    assert captured["params"] == ("marts", "orders")

    db._get_columns_postgres("events")
    assert captured["params"] == ("public", "events")

    # First-dot split keeps the rest of a dotted public name intact
    db._get_columns_postgres("public.weird.name")
    assert captured["params"] == ("public", "weird.name")


def test_postgres_sampling_quotes_schema_and_table_separately(monkeypatch):
    db = _pg_conn()
    captured = {}

    def fake_query(sql, params=None):
        captured["sql"] = sql
        return pd.DataFrame({"v": ["a", "b"]})

    monkeypatch.setattr(db, "_query_postgres", fake_query)
    vals = db._sample_distinct_values("marts.orders", "status")
    assert vals == ["a", "b"]
    # Quoting the qualified name as ONE identifier would produce "marts.orders"
    # and query a nonexistent public table.
    assert '"marts"."orders"' in captured["sql"]


# ── Multi-schema discovery: MySQL + BigQuery mirror the Postgres pattern ──────


def _mysql_conn(schemas=None):
    kwargs = dict(host="127.0.0.1", port=3306, dbname="app", user="u", password="p")
    if schemas is not None:
        kwargs["schemas"] = schemas
    return DBConnection("mysql", **kwargs)


def test_mysql_tables_default_to_home_schema_only(monkeypatch):
    """Without a stored scope, MySQL keeps its historical home-only view."""
    db = _mysql_conn()
    captured = {}

    def fake_query(sql, params=None):
        captured["sql"], captured["params"] = sql, params
        return pd.DataFrame({"table_schema": ["app"], "table_name": ["events"]})

    monkeypatch.setattr(db, "_query_mysql", fake_query)
    assert db._get_tables_mysql() == ["events"]
    assert captured["params"] == ("app", "app")  # scope + home ordering bind


def test_mysql_scope_emits_qualified_sibling_names(monkeypatch):
    db = _mysql_conn(schemas=["app", "analytics"])
    captured = {}

    def fake_query(sql, params=None):
        captured["params"] = params
        return pd.DataFrame({
            "table_schema": ["app", "app", "analytics"],
            "table_name":   ["events", "weird.name", "sessions"],
        })

    monkeypatch.setattr(db, "_query_mysql", fake_query)
    names = db._get_tables_mysql()
    # Bare for dot-free home tables, qualified otherwise — same rule as Postgres.
    assert names == ["events", "app.weird.name", "analytics.sessions"]
    assert captured["params"] == ("app", "analytics", "app")


def test_mysql_columns_bind_qualified_schema(monkeypatch):
    db = _mysql_conn(schemas=["app", "analytics"])
    captured = {}

    def fake_query(sql, params=None):
        captured["params"] = params
        return pd.DataFrame({"column_name": ["id"], "data_type": ["int"]})

    monkeypatch.setattr(db, "_query_mysql", fake_query)
    db._get_columns_mysql("analytics.sessions")
    assert captured["params"] == ("analytics", "sessions")
    db._get_columns_mysql("events")
    assert captured["params"] == ("app", "events")  # bare name → home schema


class _FakeBQTable:
    def __init__(self, table_id):
        self.table_id = table_id


class _FakeBQDataset:
    def __init__(self, dataset_id):
        self.dataset_id = dataset_id


class _FakeBQClient:
    def __init__(self, datasets):
        self._datasets = datasets  # {dataset_id: [table_id, ...]}

    def list_tables(self, dataset):
        if dataset not in self._datasets:
            raise RuntimeError("dataset not found")
        return [_FakeBQTable(t) for t in self._datasets[dataset]]

    def list_datasets(self):
        return [_FakeBQDataset(d) for d in self._datasets]


def _bq_conn(schemas=None):
    kwargs = dict(project_id="proj", dataset="raw",
                  credentials_json='{"type":"service_account"}')
    if schemas is not None:
        kwargs["schemas"] = schemas
    return DBConnection("bigquery", **kwargs)


def test_bigquery_tables_default_to_home_dataset(monkeypatch):
    db = _bq_conn()
    monkeypatch.setattr(db, "_bq_client",
                        lambda: _FakeBQClient({"raw": ["events"], "marts": ["orders"]}))
    assert db._get_tables_bigquery() == ["events"]


def test_bigquery_scope_emits_qualified_dataset_names(monkeypatch):
    db = _bq_conn(schemas=["raw", "marts"])
    monkeypatch.setattr(db, "_bq_client",
                        lambda: _FakeBQClient({"raw": ["events"], "marts": ["orders"]}))
    assert db._get_tables_bigquery() == ["events", "marts.orders"]


def test_bigquery_dropped_scoped_dataset_is_skipped_not_fatal(monkeypatch):
    db = _bq_conn(schemas=["raw", "gone"])
    monkeypatch.setattr(db, "_bq_client", lambda: _FakeBQClient({"raw": ["events"]}))
    assert db._get_tables_bigquery() == ["events"]


def test_bigquery_columns_split_qualified_name(monkeypatch):
    db = _bq_conn(schemas=["raw", "marts"])
    seen = {}

    class Meta:
        schema = []

    class Client(_FakeBQClient):
        def get_table(self, full):
            seen["full"] = full
            return Meta()

    monkeypatch.setattr(db, "_bq_client", lambda: Client({"raw": [], "marts": []}))
    db._get_columns_bigquery("marts.orders")
    assert seen["full"] == "proj.marts.orders"
    db._get_columns_bigquery("events")
    assert seen["full"] == "proj.raw.events"
    with pytest.raises(ValueError, match="Unsafe"):
        db._get_columns_bigquery('marts.orders"; DROP')


def test_postgres_scope_filters_discovery(monkeypatch):
    db = DBConnection("postgres", host="h", port=5432, dbname="d", user="u",
                      password="p", schemas=["public", "marts"])
    captured = {}

    def fake_query(sql, params=None):
        captured["sql"], captured["params"] = sql, params
        return pd.DataFrame({"table_schema": [], "table_name": []})

    monkeypatch.setattr(db, "_query_postgres", fake_query)
    db._get_tables_postgres()
    assert captured["params"] == ("public", "marts")
    assert "IN (%s, %s)" in captured["sql"]


def test_list_available_schemas_orders_home_first(monkeypatch):
    db = _mysql_conn()
    monkeypatch.setattr(db, "_query_mysql",
                        lambda sql, params=None: pd.DataFrame({"schema_name": ["app", "analytics"]}))
    assert db.list_available_schemas() == ["app", "analytics"]

    bq = _bq_conn()
    monkeypatch.setattr(bq, "_bq_client",
                        lambda: _FakeBQClient({"marts": [], "raw": [], "archive": []}))
    assert bq.list_available_schemas() == ["raw", "archive", "marts"]
