"""requirements.txt is generated from requirements.in — keep them honest.

The file used to be a pip freeze, so ~85 transitive packages sat pinned next to
the ~30 real ones with nothing marking the difference. Dependabot bumped them
independently of the parents that constrain them and produced sets that cannot
install. Three in one day, one of which reached production:

    pydantic_core==2.47.0  vs  pydantic 2.13.4 requiring ==2.46.4
    wrapt==2.3.0           vs  langfuse 4.0.0 requiring <2.0
    tokenizers==0.23.1     vs  transformers 5.14.1 requiring <=0.23.0

These check the structure holds. They deliberately do not run a resolver: that
needs the network, and CI already proves the set installs by installing it.
"""
import re
from pathlib import Path

import pytest

_ROOT = Path(__file__).resolve().parents[1]
_IN = _ROOT / "backend" / "requirements.in"
_TXT = _ROOT / "backend" / "requirements.txt"


def _names(path: Path) -> set[str]:
    out = set()
    for raw in path.read_text().splitlines():
        line = raw.split("#")[0].strip()
        if not line or line.startswith("-"):
            continue
        m = re.match(r"^([A-Za-z0-9._-]+)", line)
        if m:
            out.add(m.group(1).lower().replace("_", "-"))
    return out


def test_both_files_exist():
    assert _IN.exists(), "backend/requirements.in is the source of truth"
    assert _TXT.exists(), "backend/requirements.txt is the compiled output"


def test_compiled_file_is_marked_generated():
    """A hand edit here is silently lost on the next compile, so say so."""
    head = _TXT.read_text()[:400]
    assert "autogenerated" in head.lower() or "generated" in head.lower()
    assert "requirements.in" in head, "the header should name its source file"


def test_every_direct_dependency_survives_the_compile():
    missing = _names(_IN) - _names(_TXT)
    assert not missing, (
        f"declared in requirements.in but absent from the compiled output: "
        f"{sorted(missing)} — recompile with `uv pip compile backend/requirements.in "
        f"-o backend/requirements.txt --python-version 3.13 --universal`"
    )


def test_compiled_output_is_fully_pinned():
    """A range in the output means the installed set is not reproducible."""
    loose = []
    for raw in _TXT.read_text().splitlines():
        line = raw.split("#")[0].strip()
        if not line or line.startswith("-"):
            continue
        if re.match(r"^[A-Za-z0-9._-]+(\[[^\]]*\])?\s*(>=|<=|>|<|~=|!=)", line):
            loose.append(line)
    assert not loose, f"compiled output must pin exactly, found ranges: {loose[:5]}"


@pytest.mark.parametrize(
    "child, parent",
    [
        ("pydantic-core", "pydantic"),
        ("tokenizers", "transformers"),
        ("wrapt", "langfuse"),
    ],
)
def test_packages_that_broke_us_are_not_declared_direct(child, parent):
    """Each of these is pinned exactly by its parent.

    Naming one in requirements.in re-creates the exact bug: two pins for one
    package, free to drift apart. They belong in the compiled output only, where
    the resolver derives them from `parent`.
    """
    direct = _names(_IN)
    assert child not in direct, (
        f"{child} is constrained by {parent}; declaring it direct lets the two "
        f"pins drift and produces a set that cannot install"
    )
    # The parent is deliberately not asserted on: `transformers` reaches us
    # through sentence-transformers and is itself transitive. What matters is
    # only that the child is not hand-pinned, so the resolver stays the single
    # thing choosing the pair.


def test_root_requirements_still_delegates_to_backend():
    root = _ROOT / "requirements.txt"
    assert root.exists()
    body = [l.strip() for l in root.read_text().splitlines() if l.strip() and not l.startswith("#")]
    assert body == ["-r backend/requirements.txt"], (
        "root requirements.txt is expected to be a single -r include; CI and the "
        "Dockerfile both rely on it resolving the backend set"
    )
