"""
ui/report_export.py — Generate a PDF report from a DataPilot narrative.

Uses fpdf2 (pure Python) so there are no system-level dependencies.
The markdown narrative is parsed into styled paragraphs: h2 headings,
bullet points, bold spans, and body text.

Public API:
    build_pdf(task, narrative, recommendation, metric, cost_usd) -> bytes
"""

from __future__ import annotations

import re
from datetime import datetime
from io import BytesIO

from fpdf import FPDF


# ── Colours ───────────────────────────────────────────────────────────────────
_NAVY   = (15,  40,  80)
_BLUE   = (30,  90, 180)
_DARK   = (30,  30,  30)
_MUTED  = (100, 100, 100)
_WHITE  = (255, 255, 255)
_LIGHT  = (245, 247, 252)
_BORDER = (210, 218, 235)
_GREEN  = (22, 130, 70)
_AMBER  = (180, 100, 0)


def _clean(text: str) -> str:
    """Replace characters outside latin-1 with readable ASCII equivalents."""
    replacements = {
        "\u2014": "-",   # em dash
        "\u2013": "-",   # en dash
        "\u2019": "'",   # right single quote
        "\u2018": "'",   # left single quote
        "\u201c": '"',   # left double quote
        "\u201d": '"',   # right double quote
        "\u2026": "...", # ellipsis
        "\u2192": "->",  # →
        "\u2190": "<-",  # ←
        "\u00b7": "*",   # middle dot
        "\u2022": "*",   # bullet
        "\u2713": "[OK]",# check mark
        "\u2717": "[X]", # cross
        "\u2705": "[OK]",# ✅
        "\u26a0": "[!]", # ⚠
        "\ufe0f": "",    # variation selector (emoji modifier)
        "\u2728": "*",   # sparkles
    }
    for src, dst in replacements.items():
        text = text.replace(src, dst)
    # Strip any remaining non-latin-1 characters
    return text.encode("latin-1", errors="ignore").decode("latin-1")


class _PDF(FPDF):
    def __init__(self, task: str, metric: str):
        super().__init__()
        self._task   = task
        self._metric = metric
        self.set_margins(20, 20, 20)
        self.set_auto_page_break(auto=True, margin=20)

    def header(self):
        # Navy bar across the top
        self.set_fill_color(*_NAVY)
        self.rect(0, 0, 210, 14, style="F")
        self.set_xy(20, 3)
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(*_WHITE)
        self.cell(0, 8, "DataPilot - Analysis Report", ln=False)
        self.set_xy(-50, 3)
        self.set_font("Helvetica", "", 8)
        ts = datetime.now().strftime("%Y-%m-%d %H:%M")
        self.cell(30, 8, ts, align="R")
        self.set_text_color(*_DARK)
        self.ln(16)

    def footer(self):
        self.set_y(-12)
        self.set_font("Helvetica", "", 7)
        self.set_text_color(*_MUTED)
        self.cell(0, 6, f"Page {self.page_no()} - Generated by DataPilot", align="C")


def _strip_md_bold(text: str) -> list[tuple[bool, str]]:
    """Split text into (is_bold, segment) pairs by parsing **...**."""
    parts: list[tuple[bool, str]] = []
    for chunk in re.split(r"(\*\*[^*]+\*\*)", text):
        if chunk.startswith("**") and chunk.endswith("**"):
            parts.append((True, chunk[2:-2]))
        elif chunk:
            parts.append((False, chunk))
    return parts


def _write_mixed(pdf: FPDF, text: str, font_size: int = 10) -> None:
    """Write a line of text with inline bold support."""
    for is_bold, segment in _strip_md_bold(text):
        pdf.set_font("Helvetica", "B" if is_bold else "", font_size)
        pdf.write(6, _clean(segment))


def build_pdf(
    task: str,
    narrative: str,
    recommendation: str,
    metric: str = "",
    cost_usd: float = 0.0,
) -> bytes:
    """
    Build a PDF from the analysis narrative and return raw bytes.

    Args:
        task:           The analyst's task string.
        narrative:      The full markdown narrative (7-section structure).
        recommendation: One-sentence recommendation extracted from the narrative.
        metric:         Primary metric name (shown in the header card).
        cost_usd:       Estimated API cost for this run (shown in footer area).

    Returns:
        PDF bytes suitable for st.download_button.
    """
    pdf = _PDF(task=task, metric=metric)
    pdf.add_page()

    # ── Title card ─────────────────────────────────────────────────────────────
    pdf.set_fill_color(*_LIGHT)
    pdf.set_draw_color(*_BORDER)
    pdf.rect(20, pdf.get_y(), 170, 22, style="FD")
    pdf.set_xy(24, pdf.get_y() + 3)
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(*_NAVY)
    pdf.multi_cell(162, 7, _clean(task), align="L")
    pdf.set_font("Helvetica", "", 8)
    pdf.set_text_color(*_MUTED)
    meta_parts = []
    if metric:
        meta_parts.append(f"Metric: {metric}")
    if cost_usd > 0:
        meta_parts.append(f"API cost: ${cost_usd:.4f}")
    if meta_parts:
        pdf.set_x(24)
        pdf.cell(0, 5, "  ·  ".join(meta_parts))
    pdf.ln(10)

    # ── Recommendation callout ──────────────────────────────────────────────
    if recommendation:
        pdf.set_fill_color(*_GREEN)
        pdf.rect(20, pdf.get_y(), 170, 2, style="F")
        pdf.set_fill_color(235, 248, 240)
        pdf.set_draw_color(*_GREEN)
        pdf.rect(20, pdf.get_y() + 2, 170, 14, style="FD")
        pdf.set_xy(24, pdf.get_y() + 4)
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(*_GREEN)
        pdf.cell(20, 5, "Recommendation: ")
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(*_DARK)
        pdf.multi_cell(142, 5, _clean(recommendation))
        pdf.ln(6)

    # ── Narrative body ─────────────────────────────────────────────────────────
    pdf.set_text_color(*_DARK)
    _render_markdown(pdf, narrative)

    buf = BytesIO()
    pdf.output(buf)
    return buf.getvalue()


def _render_markdown(pdf: FPDF, md: str) -> None:
    """
    Walk the markdown line-by-line and render headings, bullets, and body text.
    Handles:
        ## Heading     → blue bold heading with underline
        - bullet       → indented bullet with •
        ✅ / ⚠️ lines  → treated as bullets
        blank lines    → small vertical gap
        body text      → inline bold support via **...**
    """
    for raw_line in md.splitlines():
        line = raw_line.rstrip()

        # h2 heading
        if line.startswith("## "):
            heading = _clean(line[3:].strip())
            pdf.ln(3)
            pdf.set_font("Helvetica", "B", 11)
            pdf.set_text_color(*_BLUE)
            pdf.cell(0, 7, heading, ln=True)
            # thin underline
            y = pdf.get_y() - 1
            pdf.set_draw_color(*_BLUE)
            pdf.line(20, y, 190, y)
            pdf.set_text_color(*_DARK)
            pdf.ln(1)

        # h3 heading
        elif line.startswith("### "):
            pdf.ln(2)
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(*_NAVY)
            pdf.cell(0, 6, _clean(line[4:].strip()), ln=True)
            pdf.set_text_color(*_DARK)

        # bullet (-, *, •, ✅, ⚠️)
        elif re.match(r"^[-*•]|\s*[-*•]|^[✅⚠️]", line):
            # strip leading marker
            text = re.sub(r"^[\s\-\*•✅⚠️]+", "", line).strip()
            raw_prefix = line[0] if line[0] in ("✅", "⚠") else "-"
            prefix = _clean(raw_prefix) or "-"
            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(*_DARK)
            pdf.set_x(22)
            pdf.cell(5, 6, prefix)
            pdf.set_x(27)
            _write_mixed(pdf, text, font_size=10)
            pdf.ln(6)

        # blank line
        elif not line.strip():
            pdf.ln(2)

        # body text
        else:
            pdf.set_x(20)
            pdf.set_font("Helvetica", "", 10)
            _write_mixed(pdf, line, font_size=10)
            pdf.ln(6)
